/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;
import java.util.ArrayList;

/**
 *
 * @author ychiong
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        

        // =========================
        // USERNAME PLACEHOLDER
        // =========================
        username.setText("Username");
        username.setForeground(java.awt.Color.GRAY);

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (username.getText().equals("Username")) {
                    username.setText("");
                    username.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (username.getText().isEmpty()) {
                    username.setText("Username");
                    username.setForeground(java.awt.Color.GRAY);
                }
            }
        });


        // =========================
        // PASSWORD PLACEHOLDER
        // =========================
        password.setText("Password");

        // Make "Password" visible instead of dots
        password.setEchoChar((char) 0);

        password.setForeground(java.awt.Color.GRAY);

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {

                // Remove placeholder
                if (String.valueOf(password.getPassword()).equals("Password")) {
                    password.setText("");

                    // Only hide characters when typing
                    if (!showPassword.isSelected()) {
                        password.setEchoChar('•');
                    }

                    password.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {

                // Restore placeholder if nothing was entered
                if (password.getPassword().length == 0) {
                    password.setText("Password");

                    // Show placeholder normally
                    password.setEchoChar((char) 0);

                    password.setForeground(java.awt.Color.GRAY);
                }
            }
        });


        // =========================
        // SHOW PASSWORD CHECKBOX
        // =========================
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {

                // Don't change the placeholder
                if (String.valueOf(password.getPassword()).equals("Password")) {
                    password.setEchoChar((char) 0);
                    return;
                }

                // Show password
                if (showPassword.isSelected()) {
                    password.setEchoChar((char) 0);
                }

                // Hide password
                else {
                    password.setEchoChar('•');
                }
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        loginlabel = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        submitDBbtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        password.addActionListener(this::passwordActionPerformed);

        username.addActionListener(this::usernameActionPerformed);

        loginbtn.setText("Log in");
        loginbtn.addActionListener(this::loginbtnActionPerformed);

        loginlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loginlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel.setText("Log into S.I.S");

        showPassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        showPassword.setText("Show Password");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Databases" }));

        submitDBbtn.setText("Submit");
        submitDBbtn.addActionListener(this::submitDBbtnActionPerformed);

        jMenu1.setText("Open");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Databases");

        jMenuItem1.setText("First Semester");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Second Semester");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Summer Semester");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(loginlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(loginbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitDBbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(password)
                                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPassword)))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(loginlabel)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassword))
                .addGap(18, 18, 18)
                .addComponent(loginbtn)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitDBbtn))
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messagebox(String msg, String titlebar) {
        javax.swing.JOptionPane.showMessageDialog(null, msg, titlebar, javax.swing.JOptionPane.INFORMATION_MESSAGE);   
    }
    
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        EnrollmentSystem a = new EnrollmentSystem();
        messagebox("Created " + a.newdb("1st") + " DB.", "Confirmation");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String user = username.getText().trim();
        String pass = String.valueOf(password.getPassword()).trim();

        // Check if username or password is empty
        if (user.isEmpty() || user.equals("Username")
                || pass.isEmpty() || pass.equals("Password")) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter your username and password.",
                    "Login Failed",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        EnrollmentSystem sys = new EnrollmentSystem();

        // Authenticate MySQL account
        if (sys.DBConnect(user, pass, "")) {

            EnrollmentSystem.currentUser = user;
            EnrollmentSystem.currentPassword = pass;

            // Determine user role
            if (user.equalsIgnoreCase("root")) {
                EnrollmentSystem.currentRole = "Admin";
            } else if (user.startsWith("100")) {
                EnrollmentSystem.currentRole = "Student";
            } else if (user.startsWith("300")) {
                EnrollmentSystem.currentRole = "Teacher";
            } else {
                EnrollmentSystem.currentRole = "Unknown";
            }

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Login Success! Please select a semester database and click Submit.",
                    "Authentication Successful",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            /*
             * TEMPORARY DATABASE LIST
             *
             * This part depends on how your EnrollmentSystem.getDatabases()
             * is implemented.
             */
            jComboBox1.removeAllItems();

            ArrayList<String> databases = sys.getDatabases();

            
            for (String dbName : databases) {
                jComboBox1.addItem(dbName);
            }

            if (databases.isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No semester databases found.",
                        "No Databases Found",
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );

                return;
            }

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Invalid Username or Password!",
                    "Login Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_loginbtnActionPerformed

    private void submitDBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDBbtnActionPerformed
        // TODO add your handling code here:
        // Check if the user has logged in
        if (EnrollmentSystem.currentUser == null
                || EnrollmentSystem.currentUser.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please login first!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Check if a database was selected
        if (jComboBox1.getSelectedItem() == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a semester database.",
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        String selectedDb =
                jComboBox1.getSelectedItem().toString();

        // Make sure the placeholder isn't selected
        if (selectedDb.equals("Databases")
                || selectedDb.equals("Item 1")
                || selectedDb.equals("null")) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a valid semester database.",
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        EnrollmentSystem sys = new EnrollmentSystem();

        // Save selected database
        sys.currentDB(selectedDb);

        // Connect using logged-in user's credentials
        if (sys.DBConnect(
                EnrollmentSystem.currentUser,
                EnrollmentSystem.currentPassword,
                selectedDb)) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Connected to " + selectedDb,
                    "Database Selected",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            if (EnrollmentSystem.currentRole.equals("Admin")) {

                StudentsForm studentForm = new StudentsForm();
                studentForm.setVisible(true);

            } else if (EnrollmentSystem.currentRole.equals("Student")) {

                StudentsForm studentForm = new StudentsForm();
                studentForm.setVisible(true);

            } else if (EnrollmentSystem.currentRole.equals("Teacher")) {

                TeachersForm teacherForm = new TeachersForm();
                teacherForm.setVisible(true);

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Unknown user role.",
                        "Login Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );

                return;
            }

            this.dispose();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Access Denied to database: " + selectedDb,
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_submitDBbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton submitDBbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
