/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class StudentsForm extends javax.swing.JFrame {
    String stdID;
    String sName;
    String sAdd;
    String sCourse;
    String sGender;
    String sYrLvl;
    
    public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) studTable.getModel();
        
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        String searchText = search.getText();
        if (searchText.equals("Search")) searchText = "";
        
        try{
            String query = "SELECT * FROM students WHERE concat(studID, studName, studAdd, studCrs, studGender, yrLvl) like '%" + searchText + "%'";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with SQL!");
            
            while (b.rs.next()){
                String i = b.rs.getString("studID");
                String c = b.rs.getString("studName");
                String d = b.rs.getString("studAdd");
                String t = b.rs.getString("studCrs");
                String g = b.rs.getString("studGender");
                String y = b.rs.getString("yrLvl");
                String[] items = {i, c, d, t, g, y};
                tblmodel.addRow(items);
            }
        }catch (Exception e){
            System.out.print("NOT successful with SQL!");
            e.printStackTrace();
        }
    }
    public static int okcancel(String theMessage) {
        int result = JOptionPane.showConfirmDialog(
            null,
            theMessage,
            "Alert",
            JOptionPane.OK_CANCEL_OPTION
        );

        return result;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentsForm.class.getName());

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();

        DefaultTableModel tblmodel =
                (DefaultTableModel) showsubjTable.getModel();
        tblmodel.setRowCount(0);

        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        studID = new javax.swing.JTextField();
        studName = new javax.swing.JTextField();
        studAdd = new javax.swing.JTextField();
        studCrs = new javax.swing.JTextField();
        studGender = new javax.swing.JTextField();
        yrLvl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showsubjTable = new javax.swing.JTable();
        enrollsubjbtn = new javax.swing.JButton();
        dropsubjbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubtn = new javax.swing.JMenu();
        subjectbtn = new javax.swing.JMenuItem();
        teachersbtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Course", "Gender", "Year"
            }
        ));
        studTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studTable);

        title.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(102, 204, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("Student Information System");

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        label.setText("Search");

        studID.setEnabled(false);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Course");

        jLabel5.setText("Gender");

        jLabel6.setText("Year Level");

        savebtn.setText("Save");
        savebtn.addActionListener(this::savebtnActionPerformed);

        editbtn.setText("Edit");
        editbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtnMouseClicked(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deletebtnMousePressed(evt);
            }
        });
        deletebtn.addActionListener(this::deletebtnActionPerformed);

        showsubjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "subjID", "subjCode", "subjDesc", "subjUnits", "subjSched"
            }
        ));
        showsubjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showsubjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(showsubjTable);

        enrollsubjbtn.setText("Enroll Subject");
        enrollsubjbtn.addActionListener(this::enrollsubjbtnActionPerformed);

        dropsubjbtn.setText("Drop Subject");
        dropsubjbtn.addActionListener(this::dropsubjbtnActionPerformed);

        jLabel7.setText("Enrolled Subjects");

        menubtn.setText("Menu");

        subjectbtn.setText("Subjects");
        subjectbtn.addActionListener(this::subjectbtnActionPerformed);
        menubtn.add(subjectbtn);

        teachersbtn.setText("Teachers");
        teachersbtn.addActionListener(this::teachersbtnActionPerformed);
        menubtn.add(teachersbtn);

        jMenuBar1.add(menubtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studGender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yrLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrollsubjbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dropsubjbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label))
                        .addComponent(jScrollPane2)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studCrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yrLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(savebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(enrollsubjbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropsubjbtn)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        Students c = new Students();
        
        c.newstudent(
        studName.getText(),
        studAdd.getText(),
        studCrs.getText(),
        studGender.getText(),
        yrLvl.getText()
        );
        showRecords();
    }//GEN-LAST:event_savebtnActionPerformed
    private void messagebox(String msg, String titlebar){
     JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
     }
    private void showEnrollRec() {
    DefaultTableModel tblmodel = (DefaultTableModel) showsubjTable.getModel();
    tblmodel.setRowCount(0);
    
    EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();
    
    try {
        String query = "SELECT * FROM subjects WHERE subjID IN " +
                       "(SELECT subjID FROM enroll WHERE studID = " + stdID + ")";
        
        b.rs = b.st.executeQuery(query);
        
        while (b.rs.next()) {
            String i = b.rs.getString("subjID");
            String c = b.rs.getString("subjCode");
            String d = b.rs.getString("subjDesc");
            String t = b.rs.getString("subjUnits");
            String g = b.rs.getString("subjSched");
            
            String[] item = {i, c, d, t, g};
            tblmodel.addRow(item);
        }
        
    } catch (Exception ex) {
        System.out.println("Not successful!");
        ex.printStackTrace();
    }
}
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        Students b = new Students();
        if ("".equals(studID.getText()) )
            messagebox("Select a Student to Delete first","Delete");
        else
            b.delete_student(Integer.parseInt(studID.getText()));
        
        showRecords();
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMouseClicked

    private void deletebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMousePressed

    private void studTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = studTable.getSelectedRow();
        
        if (selectedRow < 0) return;
        
        stdID = (String) studTable.getValueAt(selectedRow, 0);
        studID.setText(stdID);
        
        sName = (String) studTable.getValueAt(selectedRow, 1);
        studName.setText(sName);
        
        sAdd = (String) studTable.getValueAt(selectedRow, 2);
        studAdd.setText(sAdd);
        
        sCourse = (String) studTable.getValueAt(selectedRow, 3);
        studCrs.setText(sCourse);
        
        sGender = (String) studTable.getValueAt(selectedRow, 4);
        studGender.setText(sGender);
        
        sYrLvl = (String) studTable.getValueAt(selectedRow, 5);
        yrLvl.setText(sYrLvl);
        
        showEnrollRec();
    }//GEN-LAST:event_studTableMouseClicked

    private void editbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtnMouseClicked
        // TODO add your handling code here:
        Students c = new Students();
        
        if ("".equals(studID.getText()))
            messagebox("Select a student to update first:","Edit");
        
        else
            c.edit_student(
                    Integer.parseInt(studID.getText()),
                    studName.getText(),
                    studAdd.getText(),
                    studCrs.getText(),
                    studGender.getText(),
                    yrLvl.getText()
            );
        showRecords();
    }//GEN-LAST:event_editbtnMouseClicked

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void subjectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectbtnActionPerformed
        // TODO add your handling code here:
        SubjectsForm b = new SubjectsForm();
        b.setVisible(true);
        
        b.showRecords();
    }//GEN-LAST:event_subjectbtnActionPerformed

    private void teachersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersbtnActionPerformed
        // TODO add your handling code here:
        TeachersForm b = new TeachersForm();
        b.setVisible(true);
        
        b.showRecords();
    }//GEN-LAST:event_teachersbtnActionPerformed

    private void enrollsubjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollsubjbtnActionPerformed
        // TODO add your handling code here:
        Enrolled a = new Enrolled();
    
        int i = okcancel(
            "Enroll student ID: " + stdID +
            " to subject ID: " + a.getsubjID()
        );

        if (i == 0) {

            String result = a.enrollStud(Integer.parseInt(stdID));

            if (result.equals("Student is already Enrolled in this subject.")) {
                messagebox(result, "Enrollment Failed");
            } else {
                messagebox(result, "Success!!");
                showEnrollRec();
            }

        } else {
            messagebox("Cancel Enroll " + stdID, "Enroll");
        }
    }//GEN-LAST:event_enrollsubjbtnActionPerformed

    private void showsubjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showsubjTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = showsubjTable.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }

        Object value = showsubjTable.getValueAt(selectedRow, 0);

        if (value == null) {
            return;
        }

        int selectedSubjID = Integer.parseInt(value.toString());

        System.out.println("Selected Subject ID: " + selectedSubjID);

        Enrolled a = new Enrolled();
        a.setsubjID(selectedSubjID);
    }//GEN-LAST:event_showsubjTableMouseClicked

    private void dropsubjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropsubjbtnActionPerformed
        // TODO add your handling code here:
        Enrolled a = new Enrolled();
    
        String result = a.dropSubject(Integer.parseInt(stdID));

        if (result.equals("Drop Failed")) {
            messagebox(result, "Drop Failed");
        } else if (result.equals("Student is not Enrolled in this subject.")) {
            messagebox(result, "Drop Failed");
        } else {
            messagebox(result, "Success!!");
            showEnrollRec();
        }
    }//GEN-LAST:event_dropsubjbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton dropsubjbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton enrollsubjbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JMenu menubtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField search;
    private javax.swing.JTable showsubjTable;
    private javax.swing.JTextField studAdd;
    private javax.swing.JTextField studCrs;
    private javax.swing.JTextField studGender;
    private javax.swing.JTextField studID;
    private javax.swing.JTextField studName;
    private javax.swing.JTable studTable;
    private javax.swing.JMenuItem subjectbtn;
    private javax.swing.JMenuItem teachersbtn;
    private javax.swing.JLabel title;
    private javax.swing.JTextField yrLvl;
    // End of variables declaration//GEN-END:variables
}

