
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SubjectsForm extends javax.swing.JFrame {
    String subID;
    String subCode;
    String subDesc;
    String subUnits;
    String subSched;
    
    public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) subjTable.getModel();
        
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        String searchText = search.getText();
        if (searchText.equals("Search")) searchText = "";
        
        try{
            String query = "SELECT * FROM subjects WHERE concat(subjID, subjCode, subjDesc, subjUnits, subjSched) like '%" + searchText + "%'";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with SQL!");
            
            while (b.rs.next()){
                String i = b.rs.getString("subjID");
                String c = b.rs.getString("subjCode");
                String d = b.rs.getString("subjDesc");
                String t = b.rs.getString("subjUnits");
                String g = b.rs.getString("subjSched");
                String[] items = {i, c, d, t, g};
                tblmodel.addRow(items);
            }
        }catch (Exception e){
            System.out.print("NOT successful with SQL!");
            e.printStackTrace();
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubjectsForm.class.getName());

    /**
     * Creates new form SubjectsForm
     */
    public SubjectsForm() {
        initComponents();
        showRecords();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subjTable = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        subjID = new javax.swing.JTextField();
        subjCode = new javax.swing.JTextField();
        subjDesc = new javax.swing.JTextField();
        subjUnits = new javax.swing.JTextField();
        subjSched = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubtn = new javax.swing.JMenu();
        studentsbtn = new javax.swing.JMenuItem();
        teachersbtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Description", "Unit", "Schedule"
            }
        ));
        subjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjTable);

        title.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(102, 204, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("Subjects");

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        label.setText("Search");

        subjID.setEnabled(false);

        jLabel1.setText("ID");

        jLabel2.setText("Code");

        jLabel3.setText("Description");

        jLabel4.setText("Unit");

        jLabel5.setText("Schedule");

        savebtn.setText("Save");
        savebtn.addActionListener(this::savebtnActionPerformed);

        editbtn.setText("Edit");
        editbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtnMouseClicked(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deletebtnMousePressed(evt);
            }
        });
        deletebtn.addActionListener(this::deletebtnActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Address", "Course", "Gender", "Year level"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel6.setText("Class List");

        menubtn.setText("Menu");

        studentsbtn.setText("Students");
        studentsbtn.addActionListener(this::studentsbtnActionPerformed);
        menubtn.add(studentsbtn);

        teachersbtn.setText("Teachers");
        teachersbtn.addActionListener(this::teachersbtnActionPerformed);
        menubtn.add(teachersbtn);

        jMenuBar1.add(menubtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjCode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjSched, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjSched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(69, 69, 69)
                        .addComponent(savebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        Subjects c = new Subjects();
        
        c.newsubject(
        subjCode.getText(),
        subjDesc.getText(),
        Integer.parseInt(subjUnits.getText()),
        subjSched.getText()
        );
        showRecords();
    }//GEN-LAST:event_savebtnActionPerformed
    private void messagebox(String msg, String titlebar){
     JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
     }
    private void showClassList() {
        DefaultTableModel tblmodel =
                (DefaultTableModel) jTable1.getModel();

        tblmodel.setRowCount(0);

        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();

        try {
            String query = "SELECT * FROM students WHERE studID IN "
                    + "(SELECT studID FROM enroll WHERE subjID = " + subID + ")";

            System.out.println("subjID = " + subID);

            b.rs = b.st.executeQuery(query);

            while (b.rs.next()) {
                String i = b.rs.getString("studID");
                String c = b.rs.getString("studName");
                String d = b.rs.getString("studAdd");
                String t = b.rs.getString("studCrs");
                String g = b.rs.getString("studGender");
                String y = b.rs.getString("yrLvl");

                String[] item = {i, c, d, t, g, y};

                tblmodel.addRow(item);
            }

        } catch (Exception ex) {
            System.out.println("Not successful!");
            ex.printStackTrace();
        }
    }
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        Subjects b = new Subjects();
        if ("".equals(subjID.getText()) )
            messagebox("Select a Subject to Delete first","Delete");
        else
            b.delete_subject(Integer.parseInt(subjID.getText()));
        
        showRecords();
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMouseClicked

    private void deletebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMousePressed

    private void subjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjTableMouseClicked
        int selectedRow = subjTable.getSelectedRow();

        // Do nothing if no row is selected
        if (selectedRow < 0) {
            return;
        }

        // Prevent error when clicking the empty generated rows
        Object value = subjTable.getValueAt(selectedRow, 0);

        if (value == null) {
            return;
        }

        // Get subject ID
        subID = value.toString();
        subjID.setText(subID);

        // Get subject code
        Object codeValue = subjTable.getValueAt(selectedRow, 1);
        if (codeValue != null) {
            subCode = codeValue.toString();
            subjCode.setText(subCode);
        }

        // Get subject description
        Object descValue = subjTable.getValueAt(selectedRow, 2);
        if (descValue != null) {
            subDesc = descValue.toString();
            subjDesc.setText(subDesc);
        }

        // Get subject units
        Object unitsValue = subjTable.getValueAt(selectedRow, 3);
        if (unitsValue != null) {
            subUnits = unitsValue.toString();
            subjUnits.setText(subUnits);
        }

        // Get subject schedule
        Object schedValue = subjTable.getValueAt(selectedRow, 4);
        if (schedValue != null) {
            subSched = schedValue.toString();
            subjSched.setText(subSched);
        }

        // Store selected subject ID for enrollment
        Enrolled a = new Enrolled();
        a.setsubjID(Integer.parseInt(subID));
        
        // Store selected subject ID for teacher assignment
        Assign b = new Assign();
        b.setsubjID(Integer.parseInt(subID));

        // Display students enrolled in this subject
        showClassList();
    }//GEN-LAST:event_subjTableMouseClicked

    private void editbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtnMouseClicked
        // TODO add your handling code here:
        Subjects c = new Subjects();
        
        if ("".equals(subjID.getText()))
            messagebox("Select a subject to update first:","Edit");
        
        else
            c.edit_subject(
                    Integer.parseInt(subjID.getText()),
                    subjCode.getText(),
                    subjDesc.getText(),
                    Integer.parseInt(subjUnits.getText()),
                    subjSched.getText()
            );
        showRecords();
    }//GEN-LAST:event_editbtnMouseClicked

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void studentsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsbtnActionPerformed
        // TODO add your handling code here:
        StudentsForm b = new StudentsForm();
        b.setVisible(true);
        
        b.showRecords();
    }//GEN-LAST:event_studentsbtnActionPerformed

    private void teachersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersbtnActionPerformed
        // TODO add your handling code here:
        TeachersForm b = new TeachersForm();
        b.setVisible(true);
        
        b.showRecords();
    }//GEN-LAST:event_teachersbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SubjectsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    private javax.swing.JMenu menubtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField search;
    private javax.swing.JMenuItem studentsbtn;
    private javax.swing.JTextField subjCode;
    private javax.swing.JTextField subjDesc;
    private javax.swing.JTextField subjID;
    private javax.swing.JTextField subjSched;
    private javax.swing.JTable subjTable;
    private javax.swing.JTextField subjUnits;
    private javax.swing.JMenuItem teachersbtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
