/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TeachersForm extends javax.swing.JFrame {
    String tchID;
    String tchName;
    String tchDept;
    String tchAdd;
    String tchContact;
    String tchStatus;
    int selectedSubjID = 0;
    public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) tchTable.getModel();
    
        tblmodel.setRowCount(0);

        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();

        String searchText = search.getText();

        if (searchText.equals("Search")) {
            searchText = "";
        }

        try{
            String query = "SELECT * FROM teachers WHERE concat(tID, tName, tDept, tAdd, tContact, tStatus) "
                    + "LIKE '%" + searchText + "%'";

            b.rs = b.st.executeQuery(query);

            System.out.println("Success with SQL!");

            while (b.rs.next()){
                String i = b.rs.getString("tID");
                String c = b.rs.getString("tName");
                String d = b.rs.getString("tDept");
                String t = b.rs.getString("tAdd");
                String g = b.rs.getString("tContact");
                String y = b.rs.getString("tStatus");

                String[] items = {i, c, d, t, g, y};
                tblmodel.addRow(items);
            }

        } catch (Exception e){
            System.out.println("NOT successful with SQL!");
            e.printStackTrace();
        }
    }
    private void showAssignRec() {
        DefaultTableModel tblmodel =
                (DefaultTableModel) showsubjTable.getModel();

        tblmodel.setRowCount(0);

        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();

        try {
            String query = "SELECT * FROM subjects WHERE subjid IN "
                    + "(SELECT subjid FROM assign WHERE TID = " + tchID + ")";

            b.rs = b.st.executeQuery(query);

            while (b.rs.next()) {
                String i = b.rs.getString("subjid");
                String c = b.rs.getString("subjcode");
                String t = b.rs.getString("subjunits");
                String g = b.rs.getString("subjsched");

                String[] item = {i, c, t, g};

                tblmodel.addRow(item);
            }

        } catch (Exception ex) {
            System.out.println("Failed to show assignments: " + ex);
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeachersForm.class.getName());

    /**
     * Creates new form TeachersForm
     */
    public TeachersForm() {
        initComponents();

        DefaultTableModel tblmodel =
                (DefaultTableModel) showsubjTable.getModel();

        tblmodel.setRowCount(0);

        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tchTable = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        tDept = new javax.swing.JTextField();
        tAdd = new javax.swing.JTextField();
        tContact = new javax.swing.JTextField();
        tStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        showsubjTable = new javax.swing.JTable();
        deletesubjbtn = new javax.swing.JButton();
        assignsubjbtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubtn = new javax.swing.JMenu();
        subjectbtn = new javax.swing.JMenuItem();
        studentsbtn = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Department", "Address", "Contact", "Status"
            }
        ));
        tchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tchTable);

        title.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(102, 204, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("Teachers");

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        label.setText("Search");

        tID.setEnabled(false);

        tAdd.addActionListener(this::tAddActionPerformed);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Department");

        jLabel4.setText("Address");

        jLabel5.setText("Contact");

        jLabel6.setText("Status");

        savebtn.setText("Save");
        savebtn.addActionListener(this::savebtnActionPerformed);

        editbtn.setText("Edit");
        editbtn.addActionListener(this::editbtnActionPerformed);

        deletebtn.setText("Delete");
        deletebtn.addActionListener(this::deletebtnActionPerformed);

        showsubjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "subjID", "subjCode", "subjUnits", "subjSched"
            }
        ));
        showsubjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showsubjTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(showsubjTable);

        deletesubjbtn.setText("Delete Subject");
        deletesubjbtn.addActionListener(this::deletesubjbtnActionPerformed);

        assignsubjbtn.setText("Assign Subject");
        assignsubjbtn.addActionListener(this::assignsubjbtnActionPerformed);

        menubtn.setText("Menu");

        subjectbtn.setText("Subjects");
        subjectbtn.addActionListener(this::subjectbtnActionPerformed);
        menubtn.add(subjectbtn);

        studentsbtn.setText("Students");
        studentsbtn.addActionListener(this::studentsbtnActionPerformed);
        menubtn.add(studentsbtn);

        jMenuBar1.add(menubtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDept, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tContact, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletesubjbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assignsubjbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label)
                                    .addGap(524, 524, 524))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(assignsubjbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletesubjbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(savebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletebtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        Teachers c = new Teachers();

        c.newteacher(
            tName.getText(),
            tDept.getText(),
            tAdd.getText(),
            tContact.getText(),
            tStatus.getText()
        );

        showRecords();
    }//GEN-LAST:event_savebtnActionPerformed
    private void messagebox(String msg, String titlebar){
     JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
     }
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        Teachers c = new Teachers();

        if ("".equals(tID.getText())) {
            messagebox("Select a teacher to delete first.", "Delete Teacher");
            return;
        }

        int teacherID = Integer.parseInt(tID.getText());

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete Teacher ID: " + teacherID + "?",
                "Delete Teacher",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            boolean deleted = c.delete_teacher(teacherID);

            if (deleted) {
                messagebox("Teacher deleted successfully!", "Success!!");

                // Clear the text fields
                tID.setText("");
                tName.setText("");
                tDept.setText("");
                tAdd.setText("");
                tContact.setText("");
                tStatus.setText("");

                // Clear selected teacher
                tchID = "";

                // Clear assigned subjects table
                DefaultTableModel tblmodel =
                        (DefaultTableModel) showsubjTable.getModel();
                tblmodel.setRowCount(0);

                // Refresh teacher table
                showRecords();

            } else {
                messagebox("Teacher could not be deleted.", "Delete Teacher");
            }

        } else {
            messagebox("Delete cancelled.", "Delete Teacher");
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void tchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tchTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = tchTable.getSelectedRow();
    
        if (selectedRow < 0) {
            return;
        }

        Object value = tchTable.getValueAt(selectedRow, 0);

        if (value == null) {
            return;
        }

        tchID = value.toString();
        tID.setText(tchID);

        Object nameValue = tchTable.getValueAt(selectedRow, 1);
        Object deptValue = tchTable.getValueAt(selectedRow, 2);
        Object addValue = tchTable.getValueAt(selectedRow, 3);
        Object contactValue = tchTable.getValueAt(selectedRow, 4);
        Object statusValue = tchTable.getValueAt(selectedRow, 5);

        tName.setText(nameValue == null ? "" : nameValue.toString());
        tDept.setText(deptValue == null ? "" : deptValue.toString());
        tAdd.setText(addValue == null ? "" : addValue.toString());
        tContact.setText(contactValue == null ? "" : contactValue.toString());
        tStatus.setText(statusValue == null ? "" : statusValue.toString());

        showAssignRec();
    }//GEN-LAST:event_tchTableMouseClicked

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void subjectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectbtnActionPerformed
        // TODO add your handling code here:
        SubjectsForm b = new SubjectsForm();
        b.setVisible(true);
        
        b.showRecords();
    }//GEN-LAST:event_subjectbtnActionPerformed

    private void studentsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsbtnActionPerformed
        // TODO add your handling code here:
        StudentsForm b = new StudentsForm();
        b.setVisible(true);
        
        b.showRecords();
    }//GEN-LAST:event_studentsbtnActionPerformed

    private void tAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAddActionPerformed

    private void assignsubjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignsubjbtnActionPerformed
        // TODO add your handling code here:
        Assign a = new Assign();

        if ("".equals(tID.getText())) {
            messagebox("Please select a teacher first.", "Assign");
            return;
        }

        if (a.getsubjID() == 0) {
            messagebox("Please select a subject first.", "Assign");
            return;
        }

        int i = JOptionPane.showConfirmDialog(
                null,
                "Assign Teacher ID: " + tID.getText()
                        + " to Subject ID: " + a.getsubjID(),
                "Assign",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (i == JOptionPane.OK_OPTION) {

            String result = a.assignTchr(
                    Integer.parseInt(tID.getText())
            );

            if (result.equals("This subject is already assigned to a teacher.")) {
                messagebox(result, "Assignment Failed");
            } else {
                messagebox(result, "Success!!");
                showAssignRec();
            }

        } else {
            messagebox("Cancel Assign " + tID.getText(), "Assign");
        }
    }//GEN-LAST:event_assignsubjbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        Teachers c = new Teachers();
    
        if ("".equals(tID.getText())) {
            messagebox("Select a teacher to update first", "Edit");
        } else {
            c.edit_teacher(
                Integer.parseInt(tID.getText()),
                tName.getText(),
                tDept.getText(),
                tAdd.getText(),
                tContact.getText(),
                tStatus.getText()
            );

            showRecords();
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void showsubjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showsubjTableMouseClicked
        // TODO add your handling code here:
        Assign a = new Assign();

        int selectedRow = showsubjTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        Object value = showsubjTable.getValueAt(selectedRow, 0);

        if (value == null) {
            return;
        }

        selectedSubjID = Integer.parseInt(value.toString());

        System.out.println("Selected Subject ID: " + selectedSubjID);

        a.setsubjID(selectedSubjID);
    }//GEN-LAST:event_showsubjTableMouseClicked

    private void deletesubjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesubjbtnActionPerformed
        // TODO add your handling code here:
        Assign a = new Assign();
    
        if ("".equals(tID.getText())) {
            messagebox("Select a teacher first.", "Delete Subject");
            return;
        }

        if (a.getsubjID() == 0) {
            messagebox("Select a subject first.", "Delete Subject");
            return;
        }

        String result = a.deleteSubject(
                Integer.parseInt(tID.getText())
        );

        if (result.equals("Drop Failed")) {
            messagebox(result, "Delete Subject");
        } else if (result.equals("Teacher is not assigned to this subject.")) {
            messagebox(result, "Delete Subject");
        } else {
            messagebox(result, "Success!!");
            showAssignRec();
        }
    }//GEN-LAST:event_deletesubjbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeachersForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignsubjbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton deletesubjbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel label;
    private javax.swing.JMenu menubtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField search;
    private javax.swing.JTable showsubjTable;
    private javax.swing.JMenuItem studentsbtn;
    private javax.swing.JMenuItem subjectbtn;
    private javax.swing.JTextField tAdd;
    private javax.swing.JTextField tContact;
    private javax.swing.JTextField tDept;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tStatus;
    private javax.swing.JTable tchTable;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
